In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from tables import indexes
f = pd.read_csv('d14-22.csv')
f.head(2)

,Year,2022,2021,2020,2019,2018,2017,2016,2015,2014,...,1923,1922,1921,1920,1919,1918,1917,1916,1915,1914
0,Jan,7.48%,1.40%,2.49%,1.55%,2.07%,2.50%,1.37%,-0.09%,1.58%,...,-0.59%,-11.05%,-1.55%,16.97%,17.86%,19.66%,12.50%,2.97%,1.00%,2.04%
1,Feb,7.87%,1.68%,2.34%,1.52%,2.21%,2.74%,1.02%,-0.03%,1.13%,...,-0.59%,-8.15%,-5.64%,20.37%,14.89%,17.50%,15.39%,4.00%,1.01%,1.02%

In [ ]:
f = f.drop([12])

In [ ]:
frame = [f['1914'], f['1915'],f['1916']]

In [ ]:

fr = pd.concat(frame,axis=0,join='inner')
fr.head()

0    2.04%
1    1.02%
2    1.02%
3    0.00%
4    2.06%
dtype: object

In [ ]:
listF = [nu  for nu in range(1914,2023)]

In [ ]:
frame1 = []
for numb in range(1914,2023):
  frame1.append([f[str(numb)]])
print(frame1)

[[0     2.04%
1     1.02%
2     1.02%
3     0.00%
4     2.06%
5     1.02%
6     1.01%
7     3.03%
8     2.00%
9     1.00%
10    0.99%
11    1.00%
Name: 1914, dtype: object], [0      1.00%
1      1.01%
2      0.00%
3      2.04%
4      2.02%
5      2.02%
6      1.00%
7     -0.98%
8     -0.98%
9      0.99%
10     0.98%
11     1.98%
Name: 1915, dtype: object], [0      2.97%
1      4.00%
2      6.06%
3      6.00%
4      5.94%
5      6.93%
6      6.93%
7      7.92%
8      9.90%
9     10.78%
10    11.65%
11    12.62%
Name: 1916, dtype: object], [0     12.50%
1     15.39%
2     14.29%
3     18.87%
4     19.63%
5     20.37%
6     18.52%
7     19.27%
8     19.82%
9     19.47%
10    17.39%
11    18.10%
Name: 1917, dtype: object], [0     19.66%
1     17.50%
2     16.67%
3     12.70%
4     13.28%
5     13.08%
6     17.97%
7     18.46%
8     18.05%
9     18.52%
10    20.74%
11    20.44%
Name: 1918, dtype: object], [0     17.86%
1     14.89%
2     17.14%
3     17.61%
4     16.55%
5     14.97%
6     15.23%
7     14.94%
8     13.38%
9     13.13%
10    13.50%
11    14.55%
Name: 1919, dtype: object], [0     16.97%
1     20.37%
2     20.12%
3     21.56%
4     21.89%
5     23.67%
6     19.54%
7     14.69%
8     12.36%
9      9.95%
10     7.03%
11     2.65%
Name: 1920, dtype: object], [0      -1.55%
1      -5.64%
2      -7.11%
3     -10.84%
4     -14.08%
5     -15.79%
6     -14.90%
7     -12.81%
8     -12.50%
9     -12.06%
10    -12.12%
11    -10.83%
Name: 1921, dtype: object], [0     -11.05%
1      -8.15%
2      -8.74%
3      -7.74%
4      -5.65%
5      -5.11%
6      -5.09%
7      -6.22%
8      -5.14%
9      -4.57%
10     -3.45%
11     -2.31%
Name: 1922, dtype: object], [0     -0.59%
1     -0.59%
2      0.60%
3      1.20%
4      1.20%
5      1.80%
6      2.38%
7      3.01%
8      3.61%
9      3.59%
10     2.98%
11     2.37%
Name: 1923, dtype: object], [0      2.98%
1      2.38%
2      1.79%
3      0.59%
4      0.59%
5      0.00%
6     -0.58%
7     -0.59%
8     -0.58%
9     -0.58%
10    -0.58%
11     0.00%
Name: 1924, dtype: object], [0     0.00%
1     0.00%
2     1.17%
3     1.18%
4     1.77%
5     2.94%
6     3.51%
7     4.12%
8     3.51%
9     2.91%
10    4.65%
11    3.47%
Name: 1925, dtype: object], [0      3.47%
1      4.07%
2      2.89%
3      4.07%
4      2.89%
5      1.14%
6     -1.13%
7     -1.70%
8     -1.13%
9     -0.57%
10    -1.67%
11    -1.12%
Name: 1926, dtype: object], [0     -2.24%
1     -2.79%
2     -2.81%
3     -3.35%
4     -2.25%
5     -0.57%
6     -1.14%
7     -1.15%
8     -1.14%
9     -1.14%
10    -2.26%
11    -2.26%
Name: 1927, dtype: object], [0     -1.14%
1     -1.72%
2     -1.16%
3     -1.16%
4     -1.15%
5     -2.84%
6     -1.16%
7     -0.58%
8      0.00%
9     -1.15%
10    -0.58%
11    -1.16%
Name: 1928, dtype: object], [0     -1.16%
1      0.00%
2     -0.59%
3     -1.17%
4     -1.16%
5      0.00%
6      1.17%
7      1.17%
8      0.00%
9      0.58%
10     0.58%
11     0.59%
Name: 1929, dtype: object], [0      0.00%
1     -0.59%
2     -0.59%
3      0.59%
4     -0.59%
5     -1.75%
6     -4.05%
7     -4.62%
8     -4.05%
9     -4.62%
10    -5.20%
11    -6.40%
Name: 1930, dtype: object], [0      -7.02%
1      -7.65%
2      -7.69%
3      -8.82%
4      -9.47%
5     -10.12%
6      -9.04%
7      -8.49%
8      -9.64%
9      -9.70%
10    -10.37%
11     -9.32%
Name: 1931, dtype: object], [0     -10.06%
1     -10.19%
2     -10.26%
3     -10.32%
4     -10.46%
5      -9.93%
6      -9.93%
7     -10.60%
8     -10.67%
9     -10.74%
10    -10.20%
11    -10.27%
Name: 1932, dtype: object], [0      -9.79%
1      -9.93%
2     -10.00%
3      -9.35%
4      -8.03%
5      -6.62%
6      -3.68%
7      -2.22%
8      -1.49%
9      -0.75%
10      0.00%
11      0.76%
Name: 1933, dtype: object], [0     2.33%
1     4.72%
2     5.56%
3     5.56%
4     5.56%
5     5.51%
6     2.29%
7     1.52%
8     3.03%
9     2.27%
10    2.27%
11    1.52%
Name: 1934, dtype: object], [0     3.03%
1     3.01%
2     3.01%
3     3.76%
4     3.76%
5     2.24%
6     2.24%
7     2.24%
8     0.74%
9     1.48%
10    2.22%
11    2.99%
Name: 1935, dtype: object], [0      1.47%
1      0.73%
2      0.00%
3     -0.73%
4     -0.73%
5      0.73%
6      1.46%
7      2.19%
8      2.19%
9      2.19%
10     1.45%
11     1.45%
Name: 1936, dtype: object], [0     2.17%
1     2.17%
2     3.65%
3     4.38%
4     5.11%
5     4.35%
6     4.32%
7     3.57%
8     4.29%
9     4.29%
10    3.57%
11    2.86%
Name: 1937, dtype: object], [0      0.71%
1      0.00%
2     -0.70%
3     -0.70%
4     -2.08%
5     -2.08%
6     -2.76%
7     -2.76%
8     -3.43%
9     -4.11%
10    -3.45%
11    -2.78%
Name: 1938, dtype: object], [0     -1.41%
1     -1.42%
2     -1.42%
3     -2.82%
4     -2.13%
5     -2.13%
6     -2.13%
7     -2.13%
8      0.00%
9      0.00%
10     0.00%
11     0.00%
Name: 1939, dtype: object], [0     -0.71%
1      0.72%
2      0.72%
3      1.45%
4      1.45%
5      2.17%
6      1.45%
7      1.45%
8     -0.71%
9      0.00%
10     0.00%
11     0.71%
Name: 1940, dtype: object], [0      1.44%
1      0.71%
2      1.43%
3      2.14%
4      2.86%
5      4.26%
6      5.00%
7      6.43%
8      7.86%
9      9.29%
10    10.00%
11     9.93%
Name: 1941, dtype: object], [0     11.35%
1     12.06%
2     12.68%
3     12.59%
4     13.19%
5     10.88%
6     11.57%
7     10.74%
8      9.27%
9      9.15%
10     9.09%
11     9.03%
Name: 1942, dtype: object], [0     7.64%
1     6.96%
2     7.50%
3     8.08%
4     7.36%
5     7.36%
6     6.10%
7     4.85%
8     5.46%
9     4.19%
10    3.57%
11    2.96%
Name: 1943, dtype: object], [0     2.96%
1     2.96%
2     1.16%
3     0.58%
4     0.00%
5     0.57%
6     1.72%
7     2.31%
8     1.72%
9     1.72%
10    1.72%
11    2.30%
Name: 1944, dtype: object], [0     2.30%
1     2.30%
2     2.30%
3     1.71%
4     2.29%
5     2.84%
6     2.26%
7     2.26%
8     2.26%
9     2.26%
10    2.26%
11    2.25%
Name: 1945, dtype: object], [0      2.25%
1      1.69%
2      2.81%
3      3.37%
4      3.35%
5      3.32%
6      9.39%
7     11.60%
8     12.71%
9     14.92%
10    17.68%
11    18.13%
Name: 1946, dtype: object], [0     18.13%
1     18.79%
2     19.67%
3     19.02%
4     18.38%
5     17.65%
6     12.12%
7     11.39%
8     12.75%
9     10.58%
10     8.45%
11     8.84%
Name: 1947, dtype: object], [0     10.23%
1      9.30%
2      6.85%
3      8.68%
4      9.13%
5      9.55%
6      9.91%
7      8.89%
8      6.52%
9      6.09%
10     4.76%
11     2.99%
Name: 1948, dtype: object], [0      1.27%
1      1.28%
2      1.71%
3      0.42%
4     -0.42%
5     -0.83%
6     -2.87%
7     -2.86%
8     -2.45%
9     -2.87%
10    -1.65%
11    -2.08%
Name: 1949, dtype: object], [0     -2.08%
1     -1.26%
2     -0.84%
3     -1.26%
4     -0.42%
5     -0.42%
6      1.69%
7      2.10%
8      2.09%
9      3.80%
10     3.78%
11     5.93%
Name: 1950, dtype: object], [0     8.09%
1     9.36%
2     9.32%
3     9.32%
4     9.28%
5     8.82%
6     7.47%
7     6.58%
8     6.97%
9     6.50%
10    6.88%
11    6.00%
Name: 1951, dtype: object], [0     4.33%
1     2.34%
2     1.94%
3     2.33%
4     1.93%
5     2.32%
6     3.09%
7     3.09%
8     2.30%
9     1.91%
10    1.14%
11    0.76%
Name: 1952, dtype: object], [0     0.38%
1     0.76%
2     1.14%
3     0.76%
4     1.14%
5     1.13%
6     0.38%
7     0.75%
8     0.75%
9     1.12%
10    0.75%
11    0.75%
Name: 1953, dtype: object], [0      1.13%
1      1.51%
2      1.13%
3      0.75%
4      0.75%
5      0.37%
6      0.37%
7      0.00%
8     -0.37%
9     -0.74%
10    -0.37%
11    -0.74%
Name: 1954, dtype: object], [0     -0.74%
1     -0.74%
2     -0.74%
3     -0.37%
4     -0.74%
5     -0.74%
6     -0.37%
7     -0.37%
8      0.37%
9      0.37%
10     0.37%
11     0.38%
Name: 1955, dtype: object], [0     0.38%
1     0.38%
2     0.38%
3     0.75%
4     1.12%
5     1.87%
6     2.24%
7     1.87%
8     1.86%
9     2.23%
10    2.23%
11    2.99%
Name: 1956, dtype: object], [0     2.99%
1     3.36%
2     3.73%
3     3.72%
4     3.70%
5     3.31%
6     3.29%
7     3.66%
8     3.29%
9     2.91%
10    3.27%
11    2.90%
Name: 1957, dtype: object], [0     3.62%
1     3.25%
2     3.60%
3     3.58%
4     3.21%
5     2.85%
6     2.47%
7     2.12%
8     2.12%
9     2.12%
10    2.11%
11    1.76%
Name: 1958, dtype: object], [0     1.40%
1     1.05%
2     0.35%
3     0.35%
4     0.35%
5     0.69%
6     0.69%
7     1.04%
8     1.38%
9     1.73%
10    1.38%
11    1.73%
Name: 1959, dtype: object], [0     1.03%
1     1.73%
2     1.73%
3     1.72%
4     1.72%
5     1.72%
6     1.37%
7     1.37%
8     1.02%
9     1.36%
10    1.36%
11    1.36%
Name: 1960, dtype: object], [0     1.71%
1     1.36%
2     1.36%
3     1.02%
4     1.02%
5     0.68%
6     1.35%
7     1.01%
8     1.35%
9     0.67%
10    0.67%
11    0.67%
Name: 1961, dtype: object], [0     0.67%
1     1.01%
2     1.01%
3     1.34%
4     1.34%
5     1.34%
6     1.00%
7     1.34%
8     1.33%
9     1.33%
10    1.33%
11    1.33%
Name: 1962, dtype: object], [0     1.33%
1     1.00%
2     1.33%
3     0.99%
4     0.99%
5     1.33%
6     1.32%
7     1.32%
8     0.99%
9     1.32%
10    1.32%
11    1.65%
Name: 1963, dtype: object], [0     1.65%
1     1.65%
2     1.31%
3     1.31%
4     1.31%
5     1.31%
6     1.30%
7     0.98%
8     1.30%
9     0.97%
10    1.30%
11    0.97%
Name: 1964, dtype: object], [0     0.97%
1     0.97%
2     1.29%
3     1.62%
4     1.62%
5     1.94%
6     1.61%
7     1.94%
8     1.61%
9     1.93%
10    1.60%
11    1.92%
Name: 1965, dtype: object], [0     1.92%
1     2.56%
2     2.56%
3     2.87%
4     2.87%
5     2.53%
6     2.85%
7     3.48%
8     3.48%
9     3.79%
10    3.79%
11    3.46%
Name: 1966, dtype: object], [0     3.46%
1     2.81%
2     2.80%
3     2.48%
4     2.79%
5     2.78%
6     2.77%
7     2.45%
8     2.75%
9     2.43%
10    2.74%
11    3.04%
Name: 1967, dtype: object], [0     3.65%
1     3.95%
2     3.94%
3     3.93%
4     3.92%
5     4.20%
6     4.49%
7     4.48%
8     4.46%
9     4.75%
10    4.73%
11    4.72%
Name: 1968, dtype: object], [0     4.40%
1     4.68%
2     5.25%
3     5.52%
4     5.51%
5     5.48%
6     5.44%
7     5.71%
8     5.70%
9     5.67%
10    5.93%
11    6.20%
Name: 1969, dtype: object], [0     6.18%
1     6.15%
2     5.82%
3     6.06%
4     6.04%
5     6.01%
6     5.98%
7     5.41%
8     5.66%
9     5.63%
10    5.60%
11    5.57%
Name: 1970, dtype: object], [0     5.29%
1     5.00%
2     4.71%
3     4.16%
4     4.40%
5     4.64%
6     4.36%
7     4.62%
8     4.08%
9     3.81%
10    3.28%
11    3.27%
Name: 1971, dtype: object], [0     3.27%
1     3.51%
2     3.50%
3     3.49%
4     3.23%
5     2.71%
6     2.95%
7     2.94%
8     3.19%
9     3.42%
10    3.67%
11    3.41%
Name: 1972, dtype: object], [0     3.65%
1     3.87%
2     4.59%
3     5.06%
4     5.53%
5     6.00%
6     5.73%
7     7.38%
8     7.36%
9     7.80%
10    8.26%
11    8.71%
Name: 1973, dtype: object], [0      9.39%
1     10.02%
2     10.39%
3     10.09%
4     10.71%
5     10.86%
6     11.51%
7     10.87%
8     11.95%
9     12.06%
10    12.20%
11    12.34%
Name: 1974, dtype: object], [0     11.80%
1     11.23%
2     10.25%
3     10.21%
4      9.47%
5      9.39%
6      9.72%
7      8.60%
8      7.91%
9      7.44%
10     7.38%
11     6.94%
Name: 1975, dtype: object], [0     6.72%
1     6.29%
2     6.07%
3     6.05%
4     6.20%
5     5.97%
6     5.35%
7     5.71%
8     5.50%
9     5.46%
10    4.88%
11    4.87%
Name: 1976, dtype: object], [0     5.22%
1     5.91%
2     6.44%
3     6.95%
4     6.73%
5     6.87%
6     6.83%
7     6.62%
8     6.60%
9     6.39%
10    6.72%
11    6.70%
Name: 1977, dtype: object], [0     6.84%
1     6.43%
2     6.56%
3     6.50%
4     6.97%
5     7.41%
6     7.71%
7     7.84%
8     8.31%
9     8.93%
10    8.89%
11    9.02%
Name: 1978, dtype: object], [0      9.28%
1      9.86%
2     10.10%
3     10.49%
4     10.85%
5     10.89%
6     11.26%
7     11.82%
8     12.18%
9     12.07%
10    12.61%
11    13.29%
Name: 1979, dtype: object], [0     13.91%
1     14.18%
2     14.76%
3     14.73%
4     14.41%
5     14.39%
6     13.13%
7     12.87%
8     12.60%
9     12.77%
10    12.65%
11    12.52%
Name: 1980, dtype: object], [0     11.83%
1     11.41%
2     10.49%
3     10.00%
4      9.78%
5      9.55%
6     10.76%
7     10.80%
8     10.95%
9     10.14%
10     9.59%
11     8.92%
Name: 1981, dtype: object], [0     8.39%
1     7.62%
2     6.78%
3     6.51%
4     6.68%
5     7.06%
6     6.44%
7     5.85%
8     5.04%
9     5.14%
10    4.59%
11    3.83%
Name: 1982, dtype: object], [0     3.71%
1     3.49%
2     3.60%
3     3.90%
4     3.55%
5     2.58%
6     2.46%
7     2.56%
8     2.86%
9     2.85%
10    3.27%
11    3.79%
Name: 1983, dtype: object], [0     4.19%
1     4.60%
2     4.80%
3     4.56%
4     4.23%
5     4.22%
6     4.20%
7     4.29%
8     4.27%
9     4.26%
10    4.05%
11    3.95%
Name: 1984, dtype: object], [0     3.53%
1     3.52%
2     3.70%
3     3.69%
4     3.77%
5     3.76%
6     3.55%
7     3.35%
8     3.14%
9     3.23%
10    3.51%
11    3.80%
Name: 1985, dtype: object], [0     3.89%
1     3.11%
2     2.26%
3     1.59%
4     1.49%
5     1.77%
6     1.58%
7     1.57%
8     1.75%
9     1.47%
10    1.28%
11    1.10%
Name: 1986, dtype: object], [0     1.46%
1     2.10%
2     3.03%
3     3.78%
4     3.86%
5     3.65%
6     3.93%
7     4.28%
8     4.36%
9     4.53%
10    4.53%
11    4.43%
Name: 1987, dtype: object], [0     4.05%
1     3.94%
2     3.93%
3     3.90%
4     3.89%
5     3.97%
6     4.13%
7     4.02%
8     4.17%
9     4.25%
10    4.25%
11    4.42%
Name: 1988, dtype: object], [0     4.67%
1     4.83%
2     4.98%
3     5.12%
4     5.36%
5     5.17%
6     4.98%
7     4.71%
8     4.34%
9     4.49%
10    4.66%
11    4.65%
Name: 1989, dtype: object], [0     5.20%
1     5.26%
2     5.23%
3     4.71%
4     4.36%
5     4.67%
6     4.82%
7     5.62%
8     6.16%
9     6.29%
10    6.28%
11    6.11%
Name: 1990, dtype: object], [0     5.65%
1     5.31%
2     4.90%
3     4.89%
4     4.95%
5     4.70%
6     4.45%
7     3.80%
8     3.39%
9     2.92%
10    2.99%
11    3.06%
Name: 1991, dtype: object], [0     2.60%
1     2.82%
2     3.19%
3     3.18%
4     3.02%
5     3.09%
6     3.16%
7     3.15%
8     2.99%
9     3.20%
10    3.05%
11    2.90%
Name: 1992, dtype: object], [0     3.26%
1     3.25%
2     3.09%
3     3.23%
4     3.22%
5     3.00%
6     2.78%
7     2.77%
8     2.69%
9     2.75%
10    2.68%
11    2.75%
Name: 1993, dtype: object], [0     2.53%
1     2.52%
2     2.51%
3     2.36%
4     2.29%
5     2.49%
6     2.77%
7     2.90%
8     2.96%
9     2.61%
10    2.68%
11    2.68%
Name: 1994, dtype: object], [0     2.80%
1     2.86%
2     2.85%
3     3.05%
4     3.19%
5     3.04%
6     2.76%
7     2.62%
8     2.54%
9     2.81%
10    2.61%
11    2.54%
Name: 1995, dtype: object], [0     2.73%
1     2.65%
2     2.84%
3     2.90%
4     2.89%
5     2.75%
6     2.95%
7     2.88%
8     3.00%
9     2.99%
10    3.26%
11    3.32%
Name: 1996, dtype: object], [0     3.04%
1     3.03%
2     2.76%
3     2.50%
4     2.24%
5     2.30%
6     2.23%
7     2.23%
8     2.16%
9     2.09%
10    1.83%
11    1.70%
Name: 1997, dtype: object], [0     1.57%
1     1.44%
2     1.38%
3     1.44%
4     1.69%
5     1.68%
6     1.68%
7     1.62%
8     1.49%
9     1.49%
10    1.55%
11    1.61%
Name: 1998, dtype: object], [0     1.67%
1     1.61%
2     1.73%
3     2.28%
4     2.09%
5     1.96%
6     2.15%
7     2.26%
8     2.63%
9     2.56%
10    2.62%
11    2.69%
Name: 1999, dtype: object], [0     2.74%
1     3.22%
2     3.76%
3     3.07%
4     3.19%
5     3.73%
6     3.66%
7     3.41%
8     3.45%
9     3.45%
10    3.45%
11    3.39%
Name: 2000, dtype: object], [0     3.73%
1     3.53%
2     2.92%
3     3.27%
4     3.62%
5     3.25%
6     2.72%
7     2.72%
8     2.65%
9     2.13%
10    1.90%
11    1.55%
Name: 2001, dtype: object], [0     1.14%
1     1.14%
2     1.48%
3     1.64%
4     1.18%
5     1.07%
6     1.47%
7     1.80%
8     1.51%
9     2.03%
10    2.20%
11    2.38%
Name: 2002, dtype: object], [0     2.60%
1     2.98%
2     3.02%
3     2.23%
4     2.06%
5     2.11%
6     2.11%
7     2.16%
8     2.32%
9     2.04%
10    1.77%
11    1.88%
Name: 2003, dtype: object], [0     1.93%
1     1.69%
2     1.74%
3     2.29%
4     3.05%
5     3.27%
6     2.99%
7     2.65%
8     2.54%
9     3.19%
10    3.52%
11    3.26%
Name: 2004, dtype: object], [0     2.97%
1     3.01%
2     3.15%
3     3.51%
4     2.80%
5     2.53%
6     3.17%
7     3.64%
8     4.69%
9     4.35%
10    3.46%
11    3.42%
Name: 2005, dtype: object], [0     3.99%
1     3.60%
2     3.36%
3     3.55%
4     4.17%
5     4.32%
6     4.15%
7     3.82%
8     2.06%
9     1.31%
10    1.97%
11    2.54%
Name: 2006, dtype: object], [0     2.08%
1     2.42%
2     2.78%
3     2.57%
4     2.69%
5     2.69%
6     2.36%
7     1.97%
8     2.76%
9     3.54%
10    4.31%
11    4.08%
Name: 2007, dtype: object], [0     4.28%
1     4.03%
2     3.98%
3     3.94%
4     4.18%
5     5.02%
6     5.60%
7     5.37%
8     4.94%
9     3.66%
10    1.07%
11    0.09%
Name: 2008, dtype: object], [0      0.03%
1      0.24%
2     -0.38%
3     -0.74%
4     -1.28%
5     -1.43%
6     -2.10%
7     -1.48%
8     -1.29%
9     -0.18%
10     1.84%
11     2.72%
Name: 2009, dtype: object], [0     2.63%
1     2.14%
2     2.31%
3     2.24%
4     2.02%
5     1.05%
6     1.24%
7     1.15%
8     1.14%
9     1.17%
10    1.14%
11    1.50%
Name: 2010, dtype: object], [0     1.63%
1     2.11%
2     2.68%
3     3.16%
4     3.57%
5     3.56%
6     3.63%
7     3.77%
8     3.87%
9     3.53%
10    3.39%
11    2.96%
Name: 2011, dtype: object], [0     2.93%
1     2.87%
2     2.65%
3     2.30%
4     1.70%
5     1.66%
6     1.41%
7     1.69%
8     1.99%
9     2.16%
10    1.76%
11    1.74%
Name: 2012, dtype: object], [0     1.60%
1     1.98%
2     1.47%
3     1.06%
4     1.36%
5     1.75%
6     1.96%
7     1.52%
8     1.19%
9     0.96%
10    1.24%
11    1.50%
Name: 2013, dtype: object], [0     1.58%
1     1.13%
2     1.51%
3     1.95%
4     2.13%
5     2.07%
6     1.99%
7     1.70%
8     1.66%
9     1.66%
10    1.32%
11    0.76%
Name: 2014, dtype: object], [0     -0.09%
1     -0.03%
2     -0.07%
3     -0.20%
4     -0.04%
5      0.12%
6      0.17%
7      0.20%
8     -0.04%
9      0.17%
10     0.50%
11     0.73%
Name: 2015, dtype: object], [0     1.37%
1     1.02%
2     0.85%
3     1.13%
4     1.02%
5     1.01%
6     0.84%
7     1.06%
8     1.46%
9     1.64%
10    1.69%
11    2.08%
Name: 2016, dtype: object], [0     2.50%
1     2.74%
2     2.38%
3     2.20%
4     1.87%
5     1.63%
6     1.72%
7     1.94%
8     2.23%
9     2.04%
10    2.20%
11    2.11%
Name: 2017, dtype: object], [0     2.07%
1     2.21%
2     2.36%
3     2.46%
4     2.80%
5     2.87%
6     2.95%
7     2.70%
8     2.28%
9     2.52%
10    2.18%
11    1.91%
Name: 2018, dtype: object], [0     1.55%
1     1.52%
2     1.86%
3     2.00%
4     1.79%
5     1.65%
6     1.81%
7     1.75%
8     1.71%
9     1.76%
10    2.05%
11    2.29%
Name: 2019, dtype: object], [0     2.49%
1     2.34%
2     1.54%
3     0.33%
4     0.12%
5     0.65%
6     0.99%
7     1.31%
8     1.37%
9     1.18%
10    1.18%
11    1.36%
Name: 2020, dtype: object], [0     1.40%
1     1.68%
2     2.62%
3     4.16%
4     4.99%
5     5.39%
6     5.37%
7     5.25%
8     5.39%
9     6.22%
10    6.81%
11    7.04%
Name: 2021, dtype: object], [0     7.48%
1     7.87%
2     8.54%
3     8.26%
4     8.58%
5     9.06%
6     8.53%
7     8.26%
8     8.20%
9       NaN
10      NaN
11      NaN
Name: 2022, dtype: object]]

In [ ]:
frame1 = [str(nu) for nu in range(1914,2023)]
frame2 = []
for numb in frame1:
  frame2.append(f[numb])

In [ ]:

final = pd.concat(frame2,axis=0,join='inner')
final.head()

0    2.04%
1    1.02%
2    1.02%
3    0.00%
4    2.06%
dtype: object

In [ ]:
final.to_csv('InflationForArima.csv')